version: '3'
services:
  mongo-pri:
    image: mvertes/alpine-mongo
    ports:
      - 27017:27017
    command: mongod --replSet "rs0"
  mongo-sec1:
    image: mvertes/alpine-mongo
    ports:
      - 27018:27017
    command: mongod --replSet "rs0"
  mongo-sec2:
    image: mvertes/alpine-mongo
    ports:
      - 27019:27017
    command: mongod --replSet "rs0"
